# Generated by Django 3.2 on 2021-05-02 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escritorios', '0002_auto_20210501_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('numeroOAB', models.CharField(max_length=9)),
                ('nomeUsuario', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('nacionalidade', models.CharField(default='brasileiro', max_length=40)),
                ('estadoCivil', models.CharField(default='brasileiro', max_length=20)),
                ('admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 8, 50, 110255))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 8, 50, 110268))),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escritorios.escritorio')),
            ],
        ),
    ]
