# Generated by Django 3.2 on 2021-05-02 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advogado',
            old_name='sobrenome',
            new_name='sobrenomeUsuario',
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 12, 22, 513617)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 12, 22, 513604)),
        ),
    ]
