# Generated by Django 3.2 on 2021-05-02 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_auto_20210501_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 15, 58, 982287)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 15, 58, 982271)),
        ),
    ]
