# Generated by Django 3.2 on 2021-05-02 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0003_auto_20210501_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 20, 10, 599010)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 20, 10, 598996)),
        ),
    ]
