# Generated by Django 3.2 on 2021-05-02 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0004_auto_20210501_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 27, 51, 124594)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 27, 51, 124581)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='estadoCivil',
            field=models.CharField(default='solteiro', max_length=20),
        ),
    ]
