# Generated by Django 3.2 on 2021-05-02 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0005_auto_20210501_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 28, 56, 658446)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 28, 56, 658433)),
        ),
    ]
