# Generated by Django 3.2 on 2021-05-02 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0010_auto_20210501_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 55, 28, 27756)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 55, 28, 27743)),
        ),
    ]
