# Generated by Django 3.2 on 2021-05-02 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0011_auto_20210501_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 23, 21, 30, 822909)),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 23, 21, 30, 822897)),
        ),
    ]
