# Generated by Django 3.2.1 on 2021-07-03 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('indicadorId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resumo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 5, 21, 959632))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 5, 21, 959662))),
            ],
        ),
    ]
