# Generated by Django 3.2.1 on 2021-11-06 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectativaSobrevida',
            fields=[
                ('infoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataReferente', models.DateField()),
                ('idade', models.FloatField(help_text='Idade do cliente')),
                ('genero', models.CharField(help_text='genero', max_length=1)),
                ('expectativaSobrevida', models.FloatField(help_text='Expectativa de vida de homens e mulheres no Brasil')),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 314835))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('indicadorId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resumo', models.CharField(max_length=300)),
                ('descricao', models.TextField(max_length=2000)),
                ('fonte', models.CharField(max_length=300)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 314507))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 314522))),
            ],
        ),
        migrations.CreateModel(
            name='IndicesAtualizacaoMonetaria',
            fields=[
                ('indiceId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataReferente', models.DateField()),
                ('dib', models.DateField()),
                ('fator', models.FloatField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 315170))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpcaMensal',
            fields=[
                ('ipcaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataReferente', models.DateField()),
                ('valor', models.FloatField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 315872))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('SalarioId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('vigencia', models.DateField()),
                ('baseLegal', models.CharField(blank=True, max_length=50)),
                ('valor', models.FloatField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 315491))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
