# Generated by Django 3.2.1 on 2021-07-03 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 7, 28, 32439)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 7, 28, 32413)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
