# Generated by Django 3.2.1 on 2021-07-04 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0004_auto_20210703_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 13, 28, 536518)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 13, 28, 536503)),
        ),
    ]
