# Generated by Django 3.2.1 on 2021-07-09 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0005_auto_20210704_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoIBGE',
            fields=[
                ('infoId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dataReferente', models.DateField(auto_now=True)),
                ('expVidaHomem', models.IntegerField(help_text='Expectativa de vida dos homens no Brasil')),
                ('expVidaMulher', models.IntegerField(help_text='Expectativa de vida das mulheres no Brasil')),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 16, 22, 998731))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 16, 22, 998395)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 16, 22, 998379)),
        ),
    ]
