# Generated by Django 3.2.1 on 2021-07-09 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0006_auto_20210709_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 41, 5, 563938)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 41, 5, 563917)),
        ),
        migrations.AlterField(
            model_name='infoibge',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 41, 5, 564295)),
        ),
        migrations.AlterField(
            model_name='infoibge',
            name='infoId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
