# Generated by Django 3.2.1 on 2021-07-18 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0009_auto_20210709_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicesAtualizacaoMonetaria',
            fields=[
                ('indiceId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataReferente', models.DateField()),
                ('dib', models.DateField()),
                ('fator', models.FloatField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 7, 18, 19, 33, 31, 303920))),
                ('dataCadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expectativasobrevida',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 19, 33, 31, 303505)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 19, 33, 31, 303086)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 19, 33, 31, 303066)),
        ),
    ]
