# Generated by Django 3.2.1 on 2021-09-05 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0012_auto_20210822_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectativasobrevida',
            name='genero',
            field=models.CharField(default='M', help_text='genero', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expectativasobrevida',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 46, 48, 358682)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 46, 48, 358376)),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 46, 48, 358359)),
        ),
        migrations.AlterField(
            model_name='indicesatualizacaomonetaria',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 22, 46, 48, 359004)),
        ),
    ]
