# Generated by Django 3.2.1 on 2021-11-06 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncIpca',
            fields=[
                ('syncId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataSync', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 11, 9, 26, 316321))),
                ('qtdSync', models.IntegerField()),
            ],
        ),
    ]
