# Generated by Django 3.2.1 on 2022-02-09 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncIpca',
            fields=[
                ('syncId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('dataSync', models.DateTimeField(default=django.utils.timezone.now)),
                ('qtdSync', models.IntegerField()),
            ],
            options={
                'db_table': 'SyncIpca',
            },
        ),
    ]
