# Generated by Django 3.2 on 2021-05-02 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 19, 52, 9, 566986)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 19, 52, 9, 566970)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='escritorioId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
