# Generated by Django 3.2.1 on 2021-05-19 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0003_auto_20210516_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritorio',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='escritorio',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 21, 28, 13, 425035)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 21, 28, 13, 425001)),
        ),
    ]
