# Generated by Django 3.2.1 on 2021-05-22 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0004_auto_20210518_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 22, 3, 28, 403413)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 22, 3, 28, 403397)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
