# Generated by Django 3.2.1 on 2021-07-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0002_auto_20210605_2023'),
        ('escritorios', '0005_auto_20210605_2024'),
    ]

    operations = [
    ]
