# Generated by Django 3.2.1 on 2021-08-08 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0006_merge_0002_auto_20210605_2023_0005_auto_20210605_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 16, 51, 46, 308229)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 16, 51, 46, 308229)),
        ),
    ]
