# Generated by Django 3.2 on 2021-05-02 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0008_auto_20210501_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 31, 13, 255716)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 31, 13, 255698)),
        ),
    ]
