# Generated by Django 3.2 on 2021-05-02 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0014_auto_20210501_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='qtdChaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 23, 50, 57, 930605)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 23, 50, 57, 930587)),
        ),
    ]
