# Generated by Django 3.2.1 on 2021-05-09 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0018_auto_20210505_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 6, 48, 180694)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 6, 48, 180679)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='inscEstadual',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='nomeEscritorio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
