# Generated by Django 3.2.1 on 2021-05-09 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0019_auto_20210508_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 8, 16, 72933)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 8, 16, 72918)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='inscEstadual',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
