# Generated by Django 3.2.1 on 2021-05-09 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0024_auto_20210508_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 13, 27, 366630)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 13, 27, 366614)),
        ),
    ]
