# Generated by Django 3.2.1 on 2021-05-09 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0025_auto_20210508_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 33, 31, 315048)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 33, 31, 315030)),
        ),
    ]
