# Generated by Django 3.2.1 on 2021-05-09 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorios', '0026_auto_20210508_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 23, 34, 49, 209592)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 23, 34, 49, 209576)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='senha',
            field=models.CharField(max_length=80),
        ),
    ]
