# Generated by Django 3.2.1 on 2022-02-09 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciasLei91',
            fields=[
                ('carenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('dataImplemento', models.DateField()),
                ('tempoContribuicao', models.IntegerField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792927))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792940))),
            ],
            options={
                'db_table': 'CarenciasLei91',
            },
        ),
        migrations.CreateModel(
            name='ConvMon',
            fields=[
                ('convMonId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMoeda', models.CharField(max_length=20)),
                ('fator', models.BigIntegerField()),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField(blank=True, null=True)),
                ('conversao', models.CharField(choices=[('V', 'Valorizou'), ('D', 'Desvalorizou')], default='V', max_length=1)),
                ('moedaCorrente', models.BooleanField(default=False)),
                ('sinal', models.CharField(max_length=10)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792262))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792275))),
            ],
            options={
                'db_table': 'ConvMon',
            },
        ),
        migrations.CreateModel(
            name='TetosPrev',
            fields=[
                ('tetosPrevId', models.AutoField(primary_key=True, serialize=False)),
                ('dataValidade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792629))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 2, 45, 37, 792642))),
            ],
            options={
                'db_table': 'TetosPrev',
            },
        ),
    ]
