<<<<<<< Updated upstream
# Generated by Django 3.2.1 on 2021-10-31 19:11
=======
# Generated by Django 3.2.1 on 2022-01-29 20:15
>>>>>>> Stashed changes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciasLei91',
            fields=[
                ('carenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('dataImplemento', models.DateField()),
                ('tempoContribuicao', models.IntegerField()),
<<<<<<< Updated upstream
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 27194))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 27207))),
=======
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187830))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187842))),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'CarenciasLei91',
            },
        ),
        migrations.CreateModel(
            name='ConvMon',
            fields=[
                ('convMonId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMoeda', models.CharField(max_length=20)),
                ('fator', models.BigIntegerField()),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField(blank=True, null=True)),
                ('conversao', models.CharField(choices=[('V', 'Valorizou'), ('D', 'Desvalorizou')], default='V', max_length=1)),
                ('moedaCorrente', models.BooleanField(default=False)),
                ('sinal', models.CharField(max_length=10)),
<<<<<<< Updated upstream
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 26580))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 26595))),
=======
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187165))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187179))),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'ConvMon',
            },
        ),
        migrations.CreateModel(
            name='TetosPrev',
            fields=[
                ('tetosPrevId', models.AutoField(primary_key=True, serialize=False)),
                ('dataValidade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
<<<<<<< Updated upstream
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 26936))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 11, 53, 26950))),
=======
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187528))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 15, 20, 187540))),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'TetosPrev',
            },
        ),
    ]
