# Generated by Django 3.2.1 on 2021-10-28 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciasLei91',
            fields=[
                ('carenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('dataImplemento', models.DateField()),
                ('tempoContribuicao', models.IntegerField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 87171))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 87206))),
            ],
        ),
        migrations.CreateModel(
            name='ConvMon',
            fields=[
                ('convMonId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMoeda', models.CharField(max_length=20)),
                ('fator', models.BigIntegerField()),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField(blank=True, null=True)),
                ('conversao', models.CharField(choices=[('V', 'Valorizou'), ('D', 'Desvalorizou')], default='V', max_length=1)),
                ('moedaCorrente', models.BooleanField(default=False)),
                ('sinal', models.CharField(max_length=10)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 85518))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 85551))),
            ],
        ),
        migrations.CreateModel(
            name='TetosPrev',
            fields=[
                ('tetosPrevId', models.AutoField(primary_key=True, serialize=False)),
                ('dataValidade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 86462))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 21, 52, 27, 86491))),
            ],
        ),
    ]
