# Generated by Django 3.2 on 2021-05-02 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0005_auto_20210502_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 8, 24, 83722)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 8, 24, 83710)),
        ),
    ]
