# Generated by Django 3.2.1 on 2021-07-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_auto_20210605_2024'),
        ('ferramentas', '0005_auto_20210605_2024'),
    ]

    operations = [
    ]
