# Generated by Django 3.2 on 2021-05-02 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0008_auto_20210502_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convmon',
            name='convMonId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 46, 38, 533626)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 46, 38, 533615)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 46, 38, 533980)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 20, 46, 38, 533968)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='tetosPrevId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
