# Generated by Django 3.2.1 on 2021-07-09 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0010_auto_20210709_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 34, 39, 285102)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 34, 39, 285087)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 34, 39, 285440)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 34, 39, 285426)),
        ),
    ]
