# Generated by Django 3.2.1 on 2021-05-07 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0015_auto_20210505_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 4, 22, 76559)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataFinal',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 4, 22, 76547)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 4, 22, 76908)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 4, 22, 76894)),
        ),
    ]
