# Generated by Django 3.2.1 on 2021-05-07 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0016_auto_20210506_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 14, 640273)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 14, 640262)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 14, 640625)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 14, 640614)),
        ),
    ]
