# Generated by Django 3.2.1 on 2021-08-22 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0017_auto_20210718_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciasLei91',
            fields=[
                ('carenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('dataImplemento', models.DateField()),
                ('tempoContribuicao', models.IntegerField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201852))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201864))),
            ],
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201242)),
        ),
        migrations.AlterField(
            model_name='convmon',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201230)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201581)),
        ),
        migrations.AlterField(
            model_name='tetosprev',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 39, 4, 201570)),
        ),
    ]
